# Dockerfile to build a scaled down version with own General and Azure tooling
FROM ubuntu:latest

# Install prerequisites
RUN rm /bin/sh && \
    ln -s /bin/bash /bin/sh && \
    apt-get update -qq && \
    apt-get install -y\
      apt-transport-https \      
      software-properties-common\
      dirmngr\
      python2.7\
      python3\
      python3-distutils\
      python3-venv\
      curl\
      unzip\
      git && \
      curl -O https://bootstrap.pypa.io/get-pip.py && \
      python3 get-pip.py 

# Add Azure CLI/GCP/Kubectl source and package keys
RUN . /etc/os-release &&\
      echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $UBUNTU_CODENAME main" | \
            tee /etc/apt/sources.list.d/azure-cli.list && \
      apt-key --keyring /etc/apt/trusted.gpg.d/Microsoft.gpg adv \
      --keyserver packages.microsoft.com \
      --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF && \
      echo "deb http://packages.cloud.google.com/apt cloud-sdk-$UBUNTU_CODENAME main" | \
            tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
      curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
      echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list && \
      curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
      apt-get update -qq

# Install the Azure CLI    
ARG AZURE_CLI_VERSION
RUN if [ -z "$AZURE_CLI_VERSION" ] ; then \
      apt-get install -y azure-cli; \
    else \
      . /etc/os-release &&\
        apt-get install -y azure-cli=$AZURE_CLI_VERSION-1~$UBUNTU_CODENAME; \
    fi && \
    echo "source /etc/bash_completion.d/azure-cli" >> /root/.bashrc
############### End Install Azure CLI

############### Install Azure Python SDK for Python Dev
ARG AZURE_SDK_VERSION
RUN if [ -z "$AZURE_SDK_VERSION" ] ; then \
      pip3 install azure; \
    else \
      pip3 install azure=$AZURE_SDK_VERSION; \
    fi 
############### End Install Azure Python SDK for Python Dev

############### Install Terraform
ARG TERRAFORM_VERSION
RUN curl https://releases.hashicorp.com/terraform/0.12.23/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -o /tmp/terraform.zip && \
      mkdir -p ${HOME}/bin && \
       cd ${HOME}/bin && \
       unzip /tmp/terraform.zip && \
       rm /tmp/terraform.zip && \
       echo 'export PATH=${HOME}/bin:${PATH}' >> ~/.bashrc
############### End Install Terraform

# Install helm by retrieving install script from git and executing
ARG HELM_VERSION
RUN if [ -z "$HELM_VERSION" ] ; then \
      curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > install_helm.sh &&  /bin/sh install_helm.sh; \
    else \
      curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > install_helm.sh &&  /bin/sh install_helm.sh --version v${HELM_VERSION}; \
    fi

# Install kubectl  by retrieving install script and executing
ARG KUBECTL_VERSION
RUN if [ -z "$KUBECTL_VERSION" ] ; then \
      apt-get install -y kubectl; \
    else \
      apt-get install -y kubectl=$KUBECTL_VERSION-00; \
    fi

# Log in to Azure and Git (VS Code handles the credentials assuming I've used them there)
ARG AZURE_CLI_LOGIN_TENANT_ID
ARG AZURE_CLI_LOGIN_SP_ID
ARG AZURE_CLI_LOGIN_SP_SECRET
ARG GIT_USERNAME
ARG GIT_USER_EMAIL
RUN az login --service-principal --username $AZURE_CLI_LOGIN_SP_ID --password $AZURE_CLI_LOGIN_SP_SECRET --tenant $AZURE_CLI_LOGIN_TENANT_ID && \
      git config --global user.name $GIT_USERNAME && git config --global user.email $GIT_USER_EMAIL

ENV EDITOR vim