version: '3.5'
services:
  dev:
    build: 
        context: .
        dockerfile: Dockerfile
        args:
          AZURE_CLI_LOGIN_TENANT_ID: ${AZURE_CLI_LOGIN_TENANT_ID}
          AZURE_CLI_LOGIN_SP_ID: ${AZURE_CLI_LOGIN_SP_ID}
          AZURE_CLI_LOGIN_SP_SECRET: ${AZURE_CLI_LOGIN_SP_SECRET}
          GIT_USERNAME: ${GIT_USERNAME}
          GIT_USER_EMAIL: ${GIT_USER_EMAIL}
          AZURE_CLI_VERSION: ${AZURE_CLI_VERSION}
          GCP_CLI_VERSION: ${GCP_CLI_VERSION}
          AWS_CLI_VERSION: ${AWS_CLI_VERSION}
          AZURE_SDK_VERSION: ${AZURE_SDK_VERSION}
          HELM_VERSION: ${HELM_VERSION}
          TERRAFORM_VERSION: ${TERRAFORM_VERSION}
          KUBECTL_VERSION: ${KUBECTL_VERSION}
          AZURE_FUNCTIONS_TOOLS_VERSION: ${AZURE_FUNCTIONS_TOOLS_VERSION}
    tty: true