version: '3.5'
services:
  dev:
    build: 
        context: .
        args:
          AZURE_CLI_LOGIN_TENANT_ID: ${AZURE_CLI_LOGIN_TENANT_ID}
          AZURE_CLI_LOGIN_SP_ID: ${AZURE_CLI_LOGIN_SP_ID}
          AZURE_CLI_LOGIN_SP_SECRET: ${AZURE_CLI_LOGIN_SP_SECRET}
          GIT_USERNAME: ${GIT_USERNAME}
          GIT_USER_EMAIL: ${GIT_USER_EMAIL}
    tty: true